### ISSUE TITLE
Add a webui

### ISSUE THREAD

**Issue by airhorns** [gadget-inc/dateilager#3]
So operators can see the current state of various projects

**Comment by angelini** [comment]
Initial version of the webUI added in this commit: https://github.com/gadget-inc/dateilager/commit/311ccc301b781dda6b001de68508ba8c04eafb4f

At this point it's read only, but allows users to view the state of a project without using the client or needing to dig into PG tables.

I'll follow up by adding it to Gadget's toolchain so that it can be viewed in development.

**Comment by angelini** [comment]
This has now been rolled out into Gadget and runs on port 3333 for everyone using Nix.

Plenty of new features to be added, but for now it's a simple view of what's in DL and we can open new issues for feature requests.

https://github.com/gadget-inc/gadget/pull/1790
